name: My First Workflow

# # Automatic Trigger
# on:
#   push:
#     branches:
#       - main

# #manual trigger
# on:
#   workflow_dispatch

# Scheduled Trigger
on:
  schedule:
    - cron: 25 16 * * *


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Print a message
      run: echo "Hello, world!"
