name: My First Workflow

# # Automatic Trigger
# on:
#   push:
#     branches:
#       - main


on:
# # manual trigger
#   push:
#     branches:
#       - main
  workflow_dispatch:
  push:
    branches:
      - main
  # Automatic Trigger
  pull_request:
    branches:
      - main
  # Scheduled Trigger
  schedule:
    - cron: '32 * * * 1-5'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Print a message
      run: echo "Hello, world!"
